SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `csc480`
--

-- --------------------------------------------------------

DROP TABLE IF EXISTS `ACTIVITY_LOG`;
DROP TABLE IF EXISTS `USERDETAIL_AUTHORITY`;
DROP TABLE IF EXISTS `USERDETAIL`;
DROP TABLE IF EXISTS `AUTHORITIES`;
DROP TABLE IF EXISTS `TIMECARD`;
DROP TABLE IF EXISTS `MEMBER_CONDITION`;
DROP TABLE IF EXISTS `MEMBER_CONTACT`;
DROP TABLE IF EXISTS `MEMBER_GUARDIAN`;
DROP TABLE IF EXISTS `MEMBER_MEDICATION`;
DROP TABLE IF EXISTS `MEMBER`;
DROP TABLE IF EXISTS `GUARDIAN`;
DROP TABLE IF EXISTS `SITE`;
DROP TABLE IF EXISTS `ACTIVITY`;
DROP TABLE IF EXISTS `EMPLOYEE`;

--
-- Definition of table `SITE`
--

CREATE TABLE `SITE` (
  `SITE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`SITE_ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=latin1;



--
-- Definition of table `EMPLOYEE`
--

CREATE TABLE `EMPLOYEE` (
  `EMPLOYEE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PREFIX` varchar(4) DEFAULT NULL,
  `FIRST_NAME` varchar(64) DEFAULT NULL,
  `LAST_NAME` varchar(64) DEFAULT NULL,
  `MIDDLE_NAME` varchar(64) DEFAULT NULL,
  `NICK_NAME` varchar(64) DEFAULT NULL,
  `SUFFIX` varchar(64) DEFAULT NULL,
  `BIRTH_DT` date DEFAULT NULL,
  `SEX` varchar(10) DEFAULT NULL,
  `ETHNICITY` varchar(64) DEFAULT NULL,
  `HOME_PHONE` varchar(64) DEFAULT NULL,
  `CELL_PHONE` varchar(64) DEFAULT NULL,
  `WORK_PHONE` varchar(64) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `ADDRESS1` varchar(150) DEFAULT NULL,
  `ADDRESS2` varchar(150) DEFAULT NULL,
  `CITY` varchar(100) DEFAULT NULL,
  `STATE` varchar(2) DEFAULT NULL,
  `ZIP` varchar(10) DEFAULT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `START_DT` date DEFAULT NULL,
  `TERMINATION_DT` date DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  KEY `Index_Name` (`LAST_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



--
-- Table structure for table `AUTHORITIES`
--

CREATE TABLE  `AUTHORITIES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUTHORITY` varchar(100) NOT NULL,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `AUTHORITY_UNIQUE` (`AUTHORITY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `AUTHORITIES`
--


-- --------------------------------------------------------

--
-- Table structure for table `USERDETAIL`
--

CREATE TABLE  `USERDETAIL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `FIRSTNAME` varchar(50) DEFAULT NULL,
  `LASTNAME` varchar(50) DEFAULT NULL,
  `ENABLED` smallint(6) DEFAULT '0',
  `EMAIL` varchar(100) DEFAULT NULL,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `REGION` varchar(20) DEFAULT NULL,
  `EMPLOYEE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME_UNIQUE` (`USERNAME`),
  KEY `FK_USER_DETAIL_EMPOYEE_ID` (`EMPLOYEE_ID`) USING BTREE,
  CONSTRAINT `FK_USER_DETAIL_EMPOYEE_ID` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `USERDETAIL`
--


-- --------------------------------------------------------

--
-- Table structure for table `USERDETAIL_AUTHORITY`
--

CREATE TABLE  `USERDETAIL_AUTHORITY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUTHORITY` varchar(50) DEFAULT NULL,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USERDETAIL_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USERDETAIL_FK` (`USERDETAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Dumping data for table `USERDETAIL_AUTHORITY`
--

-- Insert the default user with password of manager
INSERT INTO USERDETAIL(ID,USERNAME,ENABLED,PASSWORD) VALUES(1,'system',1,'46acd9b575b5766fe9ed25509bf869c4d135a501ea541ca6cb95f95ba0cb1c15');
INSERT INTO USERDETAIL_AUTHORITY(ID,AUTHORITY,USERDETAIL_ID) VALUES(1,'ROLE_ADMINISTRATOR',1);


--
-- Definition of table `ACTIVITY`
--
CREATE TABLE `ACTIVITY` (
  `ACTIVITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ACTIVITY_ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `ACTIVITY`
--

/*!40000 ALTER TABLE `ACTIVITY` DISABLE KEYS */;
/*!40000 ALTER TABLE `ACTIVITY` ENABLE KEYS */;


--
-- Definition of table `GUARDIAN`
--

CREATE TABLE `GUARDIAN` (
  `GUARDIAN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PREFIX` varchar(4) DEFAULT NULL,
  `FIRST_NAME` varchar(64) DEFAULT NULL,
  `LAST_NAME` varchar(64) DEFAULT NULL,
  `MIDDLE_NAME` varchar(64) DEFAULT NULL,
  `NICK_NAME` varchar(64) DEFAULT NULL,
  `SUFFIX` varchar(64) DEFAULT NULL,
  `HOME_PHONE` varchar(64) DEFAULT NULL,
  `CELL_PHONE` varchar(64) DEFAULT NULL,
  `WORK_PHONE` varchar(64) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `ADDRESS1` varchar(150) DEFAULT NULL,
  `ADDRESS2` varchar(150) DEFAULT NULL,
  `CITY` varchar(100) DEFAULT NULL,
  `STATE` varchar(2) DEFAULT NULL,
  `ZIP` varchar(10) DEFAULT NULL,
  `EMPLOYER` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`GUARDIAN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


--
-- Definition of table `MEMBER`
--
CREATE TABLE  `csc480`.`member` (
  `MEMBER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PREFIX` varchar(4) DEFAULT NULL,
  `FIRST_NAME` varchar(64) DEFAULT NULL,
  `LAST_NAME` varchar(64) DEFAULT NULL,
  `MIDDLE_NAME` varchar(64) DEFAULT NULL,
  `NICK_NAME` varchar(64) DEFAULT NULL,
  `SUFFIX` varchar(64) DEFAULT NULL,
  `BIRTH_DT` date DEFAULT NULL,
  `SEX` varchar(10) DEFAULT NULL,
  `ETHNICITY` varchar(64) DEFAULT NULL,
  `HOME_PHONE` varchar(64) DEFAULT NULL,
  `CELL_PHONE` varchar(64) DEFAULT NULL,
  `WORK_PHONE` varchar(64) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `ADDRESS1` varchar(150) DEFAULT NULL,
  `ADDRESS2` varchar(150) DEFAULT NULL,
  `CITY` varchar(100) DEFAULT NULL,
  `STATE` varchar(2) DEFAULT NULL,
  `ZIP` varchar(10) DEFAULT NULL,
  `START_DT` date NOT NULL,
  `TERMINATION_DT` date DEFAULT NULL,
  `SCHOOL` varchar(100) DEFAULT NULL,
  `GRADE_LEVEL` varchar(100) DEFAULT NULL,
  `TEACHER` varchar(100) DEFAULT NULL,
  `DOCTOR` varchar(100) DEFAULT NULL,
  `DOCTOR_PHONE` varchar(45) DEFAULT NULL,
  `INSURED` bit(1) DEFAULT NULL,
  `INSURANCE_GROUP_NUM` varchar(45) DEFAULT NULL,
  `INSURANCE_MEMBER_NUM` varchar(45) DEFAULT NULL,
  `PRIMARY_LANGUAGE` varchar(45) DEFAULT NULL,
  `SINGLE_PARENT_HOUSEHOLD` bit(1) DEFAULT NULL,
  `MILITARY_CHILD` bit(1) DEFAULT NULL,
  `SITE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`MEMBER_ID`),
  KEY `Index_Name` (`LAST_NAME`),
  KEY `FK_member_1` (`SITE_ID`),
  CONSTRAINT `FK_member_1` FOREIGN KEY (`SITE_ID`) REFERENCES `site` (`SITE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
--
-- Definition of table `MEMBER_CONDITION`
--

CREATE TABLE `MEMBER_CONDITION` (
  `CONDITION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `NOTES` longtext,
  `MEMBER_ID` int(11) NOT NULL,
  PRIMARY KEY (`CONDITION_ID`),
  KEY `FK_MEMBER_CONDITION_MEMBER_ID` (`MEMBER_ID`) USING BTREE,
  CONSTRAINT `FK_MEMBER_CONDITION_MEMBER_ID` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


--
-- Definition of table `MEMBER_CONTACT`
--

CREATE TABLE `MEMBER_CONTACT` (
  `EMERGENCY_CONTACT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(100) NOT NULL,
  `LAST_NAME` varchar(100) NOT NULL,
  `PHONE` varchar(100) NOT NULL,
  `MEMBER_ID` int(11) NOT NULL,
  PRIMARY KEY (`EMERGENCY_CONTACT_ID`),
  KEY `FK_MEMBER_CONTACT_MEMBER_ID` (`MEMBER_ID`) USING BTREE,
  CONSTRAINT `FK_MEMBER_CONTACT_MEMBER_ID` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


--
-- Definition of table `MEMBER_GUARDIAN`
--

CREATE TABLE `MEMBER_GUARDIAN` (
  `GUARDIAN_REF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GUARDIAN_ID` int(11) DEFAULT NULL,
  `RELATIONSHIP` varchar(45) DEFAULT NULL,
  `MEMBER_ID` int(11) NOT NULL,
  PRIMARY KEY (`GUARDIAN_REF_ID`),
  KEY `FKDAFF299616C45D3C` (`MEMBER_ID`),
  KEY `FK_MEMBER_GUARDIAN_GUARDIAN_id` (`GUARDIAN_ID`),
  CONSTRAINT `FK_MEMBER_GUARDIAN_GUARDIAN_id` FOREIGN KEY (`GUARDIAN_ID`) REFERENCES `GUARDIAN` (`GUARDIAN_ID`),
  CONSTRAINT `FKDAFF299616C45D3C` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Definition of table `MEMBER_MEDICATION`
--

CREATE TABLE `MEMBER_MEDICATION` (
  `MEDICATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `NOTES` longtext,
  `MEMBER_ID` int(11) NOT NULL,
  PRIMARY KEY (`MEDICATION_ID`),
  KEY `FKE6BB499416C45D3C` (`MEMBER_ID`),
  CONSTRAINT `FKE6BB499416C45D3C` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



--
-- Definition of table `TIMECARD`
--

CREATE TABLE `TIMECARD` (
  `TIMECARD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `CLOCKIN_TM` datetime NOT NULL,
  `CLOCKOUT_TM` datetime DEFAULT NULL,
  `MINUTES` int(11) DEFAULT NULL,
  `SITE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`TIMECARD_ID`),
  KEY `FK_TIMECARD_emloyee_id` (`EMPLOYEE_ID`),
  CONSTRAINT `FK_TIMECARD_emloyee_id` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`),
  KEY `FK_TIMECARD_SITE_id` (`SITE_ID`),
  CONSTRAINT `FK_TIMECARD_SITE_id` FOREIGN KEY (`SITE_ID`) REFERENCES `SITE` (`SITE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


--
-- Definition of table `ACTIVITY_LOG`
--

CREATE TABLE `ACTIVITY_LOG` (
  `ACTIVITY_LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SITE_ID` int(11) NOT NULL,
  `ACTIVITY_ID` int(11) NOT NULL,
  `MEMBER_ID` int(11) NOT NULL,
  `CHECKIN_TM` datetime NOT NULL,
  `CHECKOUT_TM` datetime DEFAULT NULL,
  PRIMARY KEY (`ACTIVITY_LOG_ID`),
  KEY `FK_ACTIVITY_LOG_SITE` (`SITE_ID`),
  KEY `FK_ACTIVITY_LOG_ACTIVITY` (`ACTIVITY_ID`),
  KEY `FK_ACTIVITY_LOG_MEMBER` (`MEMBER_ID`),
  CONSTRAINT `FK_ACTIVITY_LOG_MEMBER` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`),
  CONSTRAINT `FK_ACTIVITY_LOG_ACTIVITY` FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `ACTIVITY` (`ACTIVITY_ID`),
  CONSTRAINT `FK_ACTIVITY_LOG_SITE` FOREIGN KEY (`SITE_ID`) REFERENCES `SITE` (`SITE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `ACTIVITY_LOG`
--

/*!40000 ALTER TABLE `ACTIVITY_LOG` DISABLE KEYS */;
/*!40000 ALTER TABLE `ACTIVITY_LOG` ENABLE KEYS */;

